#include "test_web_server_adapter_body.inc"
#include "test_web_server_adapter_auth.inc"
#include "test_web_server_adapter_json_static.inc"
#include "test_web_server_adapter_stream_lifecycle.inc"
#include "test_web_server_adapter_main.inc"
