idf_component_register(
    SRCS
    "app_core.c"
    "app_core_sequence.c"
    INCLUDE_DIRS
    "include"
    PRIV_INCLUDE_DIRS
    "."
    REQUIRES
    macro_model
    support
    app_contracts_v2
    device_settings
    factory_reset_recovery
    provisioning
    storage
    usb_keyboard
    macro_executor
    device_controls
    wifi_ap
    auth
    web_server
    serial_console
    nvs_flash
    esp_hw_support
)

target_compile_options(
    ${COMPONENT_LIB}
    PRIVATE -Wall
            -Wextra
            -Werror
            -Wshadow
            -Wconversion
            -Wsign-conversion
            -Wformat=2
            -Wdouble-promotion
            -Wmissing-declarations
            -Wstrict-prototypes
)
