#include "macro_limits.h"
#include "unity.h"

TEST_CASE("firmware hard limits match the version 0.1 contract", "[device][limits]")
{
    TEST_ASSERT_EQUAL_UINT32(1U, APP_SCHEMA_VERSION);
    TEST_ASSERT_EQUAL_UINT32(4096U, APP_MACRO_SOURCE_MAX_BYTES);
    TEST_ASSERT_EQUAL_UINT32(4096U, APP_COMPILED_ACTION_MAX);
    TEST_ASSERT_EQUAL_UINT32(10000U, APP_DELAY_MAX_MS);
    TEST_ASSERT_EQUAL_UINT32(300000U, APP_ESTIMATED_DURATION_MAX_MS);
    TEST_ASSERT_EQUAL_UINT32(50U, APP_MACRO_SETS_MAX);
}
