if(NOT DEFINED STORAGE_MOUNT_SOURCE OR NOT EXISTS "${STORAGE_MOUNT_SOURCE}")
    message(FATAL_ERROR "storage mount source is unavailable")
endif()

file(READ "${STORAGE_MOUNT_SOURCE}" source)
string(REGEX MATCHALL "format_if_mount_failed[ \t\r\n]*=[ \t\r\n]*false" matches "${source}")
list(LENGTH matches match_count)
if(NOT match_count EQUAL 1)
    message(FATAL_ERROR "storage mount must set format_if_mount_failed=false exactly once")
endif()
if(source MATCHES "format_if_mount_failed[ \t\r\n]*=[ \t\r\n]*true|esp_littlefs_format")
    message(FATAL_ERROR "automatic LittleFS formatting is forbidden")
endif()
