#ifndef WEB_HTTP_STATUS_H
#define WEB_HTTP_STATUS_H

/* Named HTTP status codes for the JSON API. Defined as macros so the numeric
 * literals live only in macro bodies, which readability-magic-numbers exempts
 * (IgnoreMacros); call sites reference the names. */
#define WEB_HTTP_STATUS_OK 200U
#define WEB_HTTP_STATUS_ACCEPTED 202U
#define WEB_HTTP_STATUS_BAD_REQUEST 400U
#define WEB_HTTP_STATUS_UNAUTHORIZED 401U
#define WEB_HTTP_STATUS_FORBIDDEN 403U
#define WEB_HTTP_STATUS_NOT_FOUND 404U
#define WEB_HTTP_STATUS_CONFLICT 409U
#define WEB_HTTP_STATUS_PAYLOAD_TOO_LARGE 413U
#define WEB_HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE 415U
#define WEB_HTTP_STATUS_UNPROCESSABLE_ENTITY 422U
#define WEB_HTTP_STATUS_TOO_MANY_REQUESTS 429U
#define WEB_HTTP_STATUS_INTERNAL_SERVER_ERROR 500U
#define WEB_HTTP_STATUS_SERVICE_UNAVAILABLE 503U
#define WEB_HTTP_STATUS_INSUFFICIENT_STORAGE 507U

#endif
