#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define APP_V2_SETTINGS_MAGIC UINT32_C(0x324b4d45)
#define APP_V2_SETTINGS_RECORD_VERSION UINT16_C(1)
#define APP_V2_SETTINGS_RECORD_BYTES UINT16_C(344)
#define APP_V2_CREDENTIAL_VERSION UINT16_C(1)
#define APP_V2_PASSWORD_ALGORITHM_VERSION UINT16_C(1)
#define APP_V2_PASSWORD_SALT_BYTES UINT32_C(16)
#define APP_V2_PASSWORD_VERIFIER_BYTES UINT32_C(32)
#define APP_V2_DEVICE_NAME_MAX_BYTES UINT32_C(32)
#define APP_V2_WIFI_SSID_MAX_BYTES UINT32_C(32)
#define APP_V2_WIFI_PASSPHRASE_MIN_BYTES UINT32_C(8)
#define APP_V2_WIFI_PASSPHRASE_MAX_BYTES UINT32_C(63)
#define APP_V2_UUID_TEXT_BYTES UINT32_C(36)
#define APP_V2_UUID_BUFFER_BYTES UINT32_C(37)

#define APP_V2_SETTINGS_OFFSET_MAGIC UINT16_C(0)
#define APP_V2_SETTINGS_OFFSET_RECORD_VERSION UINT16_C(4)
#define APP_V2_SETTINGS_OFFSET_RECORD_LENGTH UINT16_C(6)
#define APP_V2_SETTINGS_OFFSET_CREDENTIAL_VERSION UINT16_C(8)
#define APP_V2_SETTINGS_OFFSET_PASSWORD_ALGORITHM UINT16_C(10)
#define APP_V2_SETTINGS_OFFSET_PASSWORD_ITERATIONS UINT16_C(12)
#define APP_V2_SETTINGS_OFFSET_PASSWORD_SALT UINT16_C(16)
#define APP_V2_SETTINGS_OFFSET_PASSWORD_VERIFIER UINT16_C(32)
#define APP_V2_SETTINGS_OFFSET_NEXT_BLOB_ID UINT16_C(64)
#define APP_V2_SETTINGS_OFFSET_SEND_MODE UINT16_C(72)
#define APP_V2_SETTINGS_OFFSET_RETENTION_TARGET UINT16_C(73)
#define APP_V2_SETTINGS_OFFSET_SHOW_SOURCE UINT16_C(74)
#define APP_V2_SETTINGS_OFFSET_REQUIRE_CONFIRMATION UINT16_C(75)
#define APP_V2_SETTINGS_OFFSET_PROVISIONED UINT16_C(76)
#define APP_V2_SETTINGS_OFFSET_STATION_CONFIGURED UINT16_C(77)
#define APP_V2_SETTINGS_OFFSET_RESERVED UINT16_C(78)
#define APP_V2_SETTINGS_OFFSET_LAST_SELECTED_PACKAGE UINT16_C(80)
#define APP_V2_SETTINGS_OFFSET_DEVICE_NAME UINT16_C(117)
#define APP_V2_SETTINGS_OFFSET_AP_SSID UINT16_C(150)
#define APP_V2_SETTINGS_OFFSET_AP_PASSPHRASE UINT16_C(183)
#define APP_V2_SETTINGS_OFFSET_STATION_SSID UINT16_C(247)
#define APP_V2_SETTINGS_OFFSET_STATION_PASSPHRASE UINT16_C(280)

typedef enum {
    APP_V2_SEND_MODE_QUICK = 0,
    APP_V2_SEND_MODE_PREVIEW = 1,
} app_v2_send_mode_t;

typedef struct {
    bool provisioned;
    uint16_t credential_version;
    uint16_t password_algorithm_version;
    uint32_t password_iterations;
    uint8_t password_salt[APP_V2_PASSWORD_SALT_BYTES];
    uint8_t password_verifier[APP_V2_PASSWORD_VERIFIER_BYTES];
    uint64_t next_blob_id;
    app_v2_send_mode_t send_mode;
    uint8_t snapshot_retention_target;
    bool show_macro_source_previews;
    bool require_serial_confirmation;
    bool station_configured;
    char last_selected_package_id[APP_V2_UUID_BUFFER_BYTES];
    char device_name[APP_V2_DEVICE_NAME_MAX_BYTES + 1U];
    char ap_ssid[APP_V2_WIFI_SSID_MAX_BYTES + 1U];
    char ap_passphrase[APP_V2_WIFI_PASSPHRASE_MAX_BYTES + 1U];
    char station_ssid[APP_V2_WIFI_SSID_MAX_BYTES + 1U];
    char station_passphrase[APP_V2_WIFI_PASSPHRASE_MAX_BYTES + 1U];
} app_v2_device_settings_t;

#ifdef __cplusplus
}
#endif
