#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define APP_V2_SETUP_ROUTE_PATH "/api/v1/setup"
#define APP_V2_SETUP_STATE_METHOD "GET"
#define APP_V2_SETUP_SUBMIT_METHOD "POST"
#define APP_V2_SETUP_AUTHENTICATION "none"
#define APP_V2_SETUP_JSON_CONTENT_TYPE "application/json"
#define APP_V2_SETUP_POST_BODY_LIMIT_NAME "jsonBodyMaxBytes"
#define APP_V2_SETUP_UNPROVISIONED_ROUTE_COUNT UINT8_C(2)
#define APP_V2_SETUP_GET_UNPROVISIONED_STATUS UINT16_C(200)
#define APP_V2_SETUP_POST_UNPROVISIONED_STATUS UINT16_C(202)
#define APP_V2_SETUP_GET_PROVISIONED_STATUS UINT16_C(404)
#define APP_V2_SETUP_POST_PROVISIONED_STATUS UINT16_C(409)
#define APP_V2_SETUP_OTHER_API_ROUTES_UNAVAILABLE UINT8_C(1)

#ifdef __cplusplus
}
#endif
