idf_component_register(
    SRCS
    "serial_console.c"
    "serial_console_confirmation.c"
    INCLUDE_DIRS
    "include"
    REQUIRES
    macro_model
    app_contracts_v2
    device_controls
    macro_executor
    wifi_ap
    device_settings
    console
    esp_driver_uart
)

target_compile_options(
    ${COMPONENT_LIB}
    PRIVATE -Wall
            -Wextra
            -Werror
            -Wshadow
            -Wconversion
            -Wsign-conversion
            -Wformat=2
            -Wdouble-promotion
            -Wmissing-declarations
            -Wstrict-prototypes
)
