#ifndef MACRO_LIMITS_H
#define MACRO_LIMITS_H

#include <stddef.h>
#include <stdint.h>

#define APP_SCHEMA_VERSION 1U
#define APP_MACRO_NAME_MAX_BYTES 64U
#define APP_MACRO_SOURCE_MAX_BYTES 4096U
#define APP_COMPILED_ACTION_MAX 4096U
#define APP_DELAY_MAX_MS 10000U
#define APP_ESTIMATED_DURATION_MAX_MS 300000U
#define APP_MACROS_PER_SET_MAX 100U
#define APP_PROCEDURES_PER_SET_MAX 50U
#define APP_STEPS_PER_PROCEDURE_MAX 200U
#define APP_MACRO_SETS_MAX 50U
#define APP_IMPORT_PACKAGE_MAX_BYTES (512U * 1024U)
#define APP_KEY_PRESS_DEFAULT_MS 8U
#define APP_INTER_KEY_DEFAULT_MS 15U
#define APP_PHYSICAL_CONFIRM_TIMEOUT_MS 20000U
#define APP_UUID_STRING_LENGTH 36U
#define APP_UUID_BUFFER_LENGTH 37U
#define APP_NAME_MAX_BYTES 64U
#define APP_DESCRIPTION_MAX_BYTES 256U
#define APP_MANUFACTURER_MAX_BYTES 64U
#define APP_MODEL_MAX_BYTES 64U
#define APP_BOARD_MAX_BYTES 32U
#define APP_PROCEDURE_NAME_MAX_BYTES 64U
#define APP_STEP_TITLE_MAX_BYTES 96U
#define APP_STEP_BODY_MAX_BYTES 1024U
#define APP_PATH_MAX_BYTES 256U
#define APP_SESSION_TABLE_MAX 8U
#define APP_SESSION_TOKEN_BYTES 32U
#define APP_CSRF_TOKEN_BYTES 32U

#endif
