#ifndef MACRO_LIMITS_H
#define MACRO_LIMITS_H

#include <stddef.h>
#include <stdint.h>

#include "app_limits_v2.h"

#define APP_SCHEMA_VERSION 1U
#define APP_MACRO_NAME_MAX_BYTES APP_V2_MACRO_NAME_MAX_BYTES
#define APP_MACRO_SOURCE_MAX_BYTES APP_V2_MACRO_SOURCE_MAX_BYTES
#define APP_COMPILED_ACTION_MAX APP_V2_COMPILED_ACTIONS_MAX
#define APP_DELAY_MAX_MS APP_V2_DELAY_DIRECTIVE_MAX_MS
#define APP_ESTIMATED_DURATION_MAX_MS APP_V2_ESTIMATED_DURATION_MAX_MS
#define APP_MACROS_PER_SET_MAX 100U
#define APP_MACRO_SETS_MAX 50U
#define APP_IMPORT_PACKAGE_MAX_BYTES (512U * 1024U)

/* Retired v1 repository limits remain only until the Phase 2 repository removal.
 * New v2 production code must use app_limits_v2.h directly. */
#define APP_SET_FILE_MAX_BYTES (32U * 1024U)
#define APP_USER_DATA_MAX_BYTES (480U * 1024U)
#define APP_KEY_PRESS_DEFAULT_MS 8U
#define APP_INTER_KEY_DEFAULT_MS 15U
#define APP_PHYSICAL_CONFIRM_TIMEOUT_MS                                                   \
    (APP_V2_SERIAL_CONFIRMATION_TIMEOUT_SECONDS * UINT32_C(1000))
#define APP_UUID_STRING_LENGTH 36U
#define APP_UUID_BUFFER_LENGTH 37U
#define APP_NAME_MAX_BYTES APP_V2_PACKAGE_NAME_MAX_BYTES
#define APP_DESCRIPTION_MAX_BYTES 256U
#define APP_MANUFACTURER_MAX_BYTES 64U
#define APP_MODEL_MAX_BYTES 64U
#define APP_BOARD_MAX_BYTES 32U
#define APP_PATH_MAX_BYTES 256U
#define APP_SESSION_TABLE_MAX APP_V2_ACTIVE_SESSIONS_MAX
#define APP_SESSION_TOKEN_BYTES 32U

#endif
